<head>
    <title>Sortera skivorna</title>
    <meta content = "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name = "viewport" />
    <link rel="stylesheet" type="text/css" href="static/css/stylesheet.css">
    <link rel="icon" type="image/x-icon" href="static/img/favicon.ico">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="static/js/main.js"></script>
</head>
