<div class="header">
    <h1>Skivorna</h1>
    <div class="search">
        Sök <input type="text" id="search">
    </div>
    <div class="buttons">
        <button type="button" id="show_filters">&#9660;</button>
        <button type="button" id="show_orders">&#8645;</button>
        <button type="button" id="reload">&#8635;</button>
    </div>
    <div id="counter">0</div>
    <div class="filter_container dropdown" style="display:none">
        <div id="filters"></div>
        <div class="new_filter">
            <select class="filter_attribute">
                <option value="artist">Artist</option>
                <option value="format">Format</option>
                <option value="year">År</option>
            </select>
            <select class="filter_compare">
                <option value="eq">=</option>
                <option value="neq">!=</option>
                <option value="sub">~</option>
                <option value="lt">&lt;</option>
                <option value="mt">&gt;</option>
            </select>
            <input type="text" class="filter_value">
            <button type="button" class="add_filter">+</button>
        </div>
    </div>
    <div class="order_container dropdown" style="display:none">
        <div id="orders"></div>
        <div class="new_order">
            <select class="order_attribute">
                <option value="artists">Artist</option>
                <option value="format">Format</option>
                <option value="year">År</option>
            </select>
            <label for="order_reverse">Vänd</label>
            <input type="checkbox" class="order_reverse" id="order_reverse">
            <button type="button" class="add_order">+</button>
        </div>
    </div>
</div>
