<div id="status">Väntar på data...</div>
<div id="loader" style="display: none">Laddar in skivor...</div>
<div id="artist_info" style="display:none">
    <div class="name"></div><img style="display:none"><div class="description" style="display:none"></div>
    <div class="members" style="display:none"></div><div class="groups" style="display:none"></div>
</div>
<div id="collection"></div>
<div id="record-popup" style="display:none"></div>
